apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: linuxwebsite-aci
  namespace: default
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: linuxwebsite-aci
    spec:      
      containers:
        - name: linuxwebsite
          image: marcusreg.azurecr.io/linuxwebsite
          ports:
          - containerPort: 80
          imagePullPolicy: Always  
      imagePullSecrets:
      - name:  "azure-registry"
      nodeName: aci-connector